version: '3.8'
services:
  db:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_USER: Alex
      POSTGRES_PASSWORD: users_password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
