version: '3.8'
services:
  # Сервис PostgreSQL для user_service
  db:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_USER: Alex
      POSTGRES_PASSWORD: users_password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  # Zookeeper нужен для работы Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # Kafka‑брокер
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Если вы запускаете локально и хотите обращаться по localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  db-data:
